apiVersion: v1
name: cnhea-deployment
description: Install Cloud Native Hackathon Express App
keywords:
- cloudnativehackathonexpressapp 
version: 1.0.0
maintainers:
- name: Adhir Kirtikar 
  email: adhir.s.kirtikar@gmail.com 
