namespace:
  name: cnhea
 
service:
  port: 3000
  type: ClusterIP

image:
  repository: adhirkirtikar/cloudnativehackathonexpressapp 
  tag: 0.23
  pullPolicy: IfNotPresent

replicaCount: 5

resources:
  requests:
    cpu: 50m
    memory: 256Mi