apiVersion: v1
kind: Service
metadata:
  labels:
    app: cnhea
  name: cnhea
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - port: {{ .Values.service.port }} 
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: cnhea
  type: {{ .Values.service.type }}